### ISSUE TITLE
Allow setting the 'favourited' icon to a different color from accent

### ISSUE THREAD

**Issue by hyperreal64** [catppuccin/mastodon#5]
When I favourite a toot, the color of the star icon doesn't change, so it's hard to tell which toots I've favourited unless I click on the toot and look at the details and see the number change.

Can we have a setting to allow changing the color of the star on favourited toots?

I tried looking at the CSS but couldn't find anything relevant. I suppose I can dig around in the web developer tools and submit a PR, but someone more familiar with web devel would probably have a more correct and appropriate solution.

**Comment by isabelroses** [comment]
Hello, i found the issue.
I'm currently working on it right now. This should be patched soon.
Thanks for your patients.
